FROM python:latest
RUN apt-get update
COPY ./requirements.txt /
RUN pip3 install -r requirements.txt
ARG src="admin creds.csv"
ARG target="/"
COPY ${src} ${target}
RUN chmod 400 "admin creds.csv"
COPY email_analyzer.py /
COPY email_handler.py /
CMD [ "python", "./email_analyzer.py"]
